## 第5章 语句

### 5.3 条件语句

#### 5.3.1 if语句

- 在c++中，规定else与离它最近的尚未匹配的if匹配

  ````C++
  	// 错误：实际的执行过程并非像缩进格式显示的那样；else分支匹配的是内层if语句
  	if (grade % 10 >= 3)
  		if (grade % 10 > 7)
  			lettergrade += '+';
  	else lettergrade += '-';
  	
  ````

- 程序的初衷应该希望else和外层的if匹配，但这里的else分支其实是内层if语句的一部分。

```c++
	//上述等价于
	if (grade % 10 >= 3)
		if (grade % 10 > 7)
			lettergrade += '+';
		else 
			lettergrade += '-';
```

- 使用花括号控制执行路径

```c++
	if (grade % 10 >= 3) {
		if (grade % 10 > 7)
			lettergrade += '+';
	}else 
			lettergrade += '-';

```

#### 5.3.2 switch语句

- case关键字和它对应的值一起被称为case标签。case标签必须是整型常量表达式：

  ```c++
  char ch = getVal();
  int ival = 42;
  switch(ch) {
  	case 3.14:	//错误：case标签不是一个整数
  	case ival:	//错误：case标签不是一个常量
  }
  ```

##### switch内部的变量定义

- 如果需要为某个case分支定义并初始化一个变量，我们应该把变量定义在块内，从而确保后面的所有case标签都在变量的作用域之外。

  ```c++
  case true:
  {
  	//正确：声明语句位于语句块内部
  	string file_name = get_file_name();
  	//...
  }
  break;
  case false:
  	if (file_name.empty())//错误：file_name不在作用域之内
  ```

- 例子：统计元音字母的程序，使其也能统计空格、制表符、和换行符的数量。

```c++
#include<iostream>

using std::cin; using std::cout; using std::endl;

int main()
{
unsigned aCnt = 0, eCnt = 0, iCnt = 0, oCnt = 0, uCnt = 0, spaceCnt = 0, tabCnt = 0, newLineCnt = 0;
	char ch;
	while (cin >> std::noskipws >> ch)  //使用 std::noskipws可以保留默认跳过的空格。
		switch (ch)
	{
		case 'a':
		case 'A':
			++aCnt;
			break;
		case 'e':
		case 'E':
			++eCnt;
			break;
		case 'i':
		case 'I':
			++iCnt;
			break;
		case 'o':
		case 'O':
			++oCnt;
			break;
		case 'u':
		case 'U':
			++uCnt;
			break;
		case ' ':
			++spaceCnt;
			break;
		case '\t':
			++tabCnt;
			break;
		case '\n':
			++newLineCnt;
			break;
	}

	cout << "Number of vowel a(A): \t" << aCnt << '\n'
		<< "Number of vowel e(E): \t" << eCnt << '\n'
		<< "Number of vowel i(I): \t" << iCnt << '\n'
		<< "Number of vowel o(O): \t" << oCnt << '\n'
		<< "Number of vowel u(U): \t" << uCnt << '\n'
		<< "Number of space: \t" << spaceCnt << '\n'
		<< "Number of tab char: \t" << tabCnt << '\n'
		<< "Number of new line: \t" << newLineCnt << endl;
	system("pause");
	return 0;

}
```

### 5.4 迭代语句

#### 5.4.2 传统的for语句

- for语句的语法形式是

```c++
for (init-statemen;codition;expression)
	statement
```

- *init*-*statement*必须是以下三种形式中的一种：声明语句、表达式语句或者空语句
- 一般情况下，*init*-*statement*负责初始化一个值，这个值将随着循环的进行而改变。*codition*作为循环控制的条件，只要*codition*为真，就执行一次*statement*。*expression*负责修改*init*-*statement*初始化的变量，这个变量正好是*codition*检查的对象，修改发生在每次循环迭代之后。

##### for语句头的多重定义

- 和其他声明一样，*init*-*statement*也可以定义多个对象。但是只能有一条声明语句，因此，所有变量的基础类型必须相同。

#### 5.4.3 范围for语句

- 语法形式：

  ```c++
  for (declaration : expression)
  	statement;
  ```

- 这种语句可以遍历容器或其他序列的所有元素，*expression*表示的必须是一个序列，比如用花括号括起来的初始值列表、数组或者vector或string等类型的对象。*declaration*定义一个变量，序列中的每个元素都能转换成该变量得类型。

### 5.5 跳转语句

#### 5.5.1 break语句

- break语句负责终止离它最近的循环或switch语句。

#### 5.5.2 continue语句

- continue语句终止最近的循环中的当前迭代并立即开始下一次迭代。
- continue语句只能出现在for、while和do while循环的内部。

#### 5.5.3 goto语句

- goto语句的作用是从goto语句无条件跳转到同一函数内的另一条语句。

- 语法形式：

  `goto label`

  其中，*label*是用于标识一条语句的标示符。带标签语句是一种特殊的语句，在它之前有一个标示符以及一个冒号：

  `end: return;`

  ```c++
  	goto end;
  end:
  	int ix = 10;
  ```

  向后跳过一个已经执行的定义是合法的。跳回到变量定义之前意味着系统将销毁该变量，然后重新创建它：

  ```c++
  begin:
  	int sz = get_size();
  	if (sz <= 0) {
  		goto begin;
  	}
  ```

  在上面的代码中，goto语句执行后将销毁sz。

### 5.6 try语句块和异常处理

- 异常处理机制为程序中异常检测和异常处理这两部分的协作提供支持。在C++语言中，异常处理包括：
  - throw表达式，异常检测部分使用throw表达式来表示它遇到了无法处理的问题。
  - try语句块，异常处理部分使用try语句块处理异常。try语句块以关键字try开始，并以一个或多个catch子句结束。try语句块中代码抛出的异常通常会被某个catch子句处理。
  - 一套异常类，用于在throw表达式和相关的catch子句之间传递异常的具体信息。

#### 5.6.1 throw表达式

- 程序的异常检测部分使用throw表达式引发一个异常。

- throw表达式包含关键字throw和紧随其后的一个表达式，其中表达式的类型就是抛出的异常类型。

  ```c++
  Sales_item item1, item2;
  cin >> item1 >> item2;
  if (item1.isbn() == item2.isbn()) {
  	cout << item1 + item2 <<endl;
  	return 0;	//表示成功
  }else {
  	cout << "Data must refer to same ISBN" << endl;
  	return -1;	//表示失败
  }
  ```

  此例中，改写程序使得检查完成后不再直接输出一条信息，而是抛出一个异常：

  ```c++
  if (item1.isbn() != item2.isbn())
  	throw runtime_error("Data must refer to same ISBN");
  //如果程序执行到这里，表示两个ISBN是相同的。
  cout<< item1 + item2 <<endl;
  ```

  类型runtime_error是标准库异常类型的一种。

#### 5.6.2 try语句块

- try语句块的通用语法形式是：

  ```c++
  try {
  	statements
  }catch (exception-declaration){
  	handler-statements;
  }catch (exception-declaration){
  	handler-statements;
  }// ...
  ```

- catch子句包含三部分：关键字catch、括号内一个对象的声明（称作异常声明）以及一个块。

#### 5.6.3 标准异常

- 标准库定义的异常类，它们分别定义在4个头文件中：

  - exception头文件定义了最通常的异常类exception，它只报告异常的发生，不提供任何额外信息。

  - stdexcept头文件定义了几种常用的异常类

    | 类名             | 说明                                           |
    | ---------------- | ---------------------------------------------- |
    | exception        | 最常见的问题                                   |
    | runtime_error    | 只有在运行时才能检测出的问题                   |
    | range_error      | 运行时错误：生成的结果超出了有意义的值域范围   |
    | overflow_error   | 运行时错误：计算上溢                           |
    | underflow_error  | 运行时错误：计算下溢                           |
    | logic_error      | 程序逻辑错误                                   |
    | domain_error     | 逻辑错误：参数对应的结果值不存在               |
    | invalid_argument | 逻辑错误：无效参数                             |
    | length_error     | 逻辑错误：试图创建一个超出该类型最大长度的对象 |
    | out_of_range     | 逻辑错误：使用一个超出有效范围的值             |

- 标准库异常类只定义了几种运算，创建、拷贝以及为异常类型的对象赋值。

  - 对于exception、bad_alloc和bad_cast对象，只能默认初始化
  - 其他异常类型的对象应该使用string对象或c风格字符串初始化，但不允许默认初始化。必须提供初始值。

- 例子：编写一段程序，从标准输入读取两个整数，输出第一个数除以第二个数的结果。

```c++
#include <iostream>
using std::cin;
using std::cout;
using std::endl;

int main() 
{
    int i, j; 
    cin >> i >> j;
    cout << i / j << endl;
 
    return 0;
}
```

修改你的程序，使得当第二个数是0时抛出异常。先不要设定`catch`子句，运行程序并真的为除数输入0，看看会发生什么？

```c++
#include <iostream>
#include <stdexcept>

int main(void)
{
    int i, j;
    std::cin >> i >> j;
    if (j == 0)
        throw std::runtime_error("divisor is 0");
    std::cout << i / j << std::endl;

    return 0;
}
```

修改上一题的程序，使用`try`语句块去捕获异常。`catch`子句应该为用户输出一条提示信息，询问其是否输入新数并重新执行`try`语句块的内容。

```c++
#include <iostream>
#include <stdexcept>
using std::cin; using std::cout; using std::endl; using std::runtime_error;

int main(void)
{
    for (int i, j; cout << "Input two integers:\n", cin >> i >> j; )
    {
        try 
        {
            if (j == 0) 
                throw runtime_error("divisor is 0");
            cout << i / j << endl;
        }
        catch (runtime_error err) 
        {
            cout << err.what() << "\nTry again? Enter y or n" << endl;
            char c;
            cin >> c;
            if (!cin || c == 'n')
                break;
        }
    }

    return 0;
}
```



